# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'warning_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WarninDialog(object):
    def setupUi(self, WarninDialog):
        WarninDialog.setObjectName("WarninDialog")
        WarninDialog.resize(591, 385)
        self.label = QtWidgets.QLabel(WarninDialog)
        self.label.setGeometry(QtCore.QRect(50, 50, 531, 231))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(WarninDialog)
        self.pushButton.setGeometry(QtCore.QRect(240, 270, 101, 51))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(WarninDialog)
        QtCore.QMetaObject.connectSlotsByName(WarninDialog)

    def retranslateUi(self, WarninDialog):
        _translate = QtCore.QCoreApplication.translate
        WarninDialog.setWindowTitle(_translate("WarninDialog", "Ошибка!"))
        self.label.setText(_translate("WarninDialog", "Кажется что-то пошло не так.\n"
" Проверьте правильность данных. "))
        self.pushButton.setText(_translate("WarninDialog", "Ок."))
